Make container size more configurable
nicolas-lang/Factorio.LongStorageTanks pull request #6
Opened 2023-03-08 13:35 UTC by krissi

This PR adds more control over the storage size while trying to communicate how the storage is calculated.

2023-03-15 21:32 UTC, nicolas-lang requested changes
Except the removal of the max size I like your changes.
Can you please review my comment, in the meantime I'll have a look on the release process, it seems like the release pipeline is broken :-(

2023-03-15 21:32 UTC, nicolas-lang commented on lib/lib_storagetank.lua
I think I remember that the max size had some kind of perforemance reason. I would prefer to keep this.

2023-03-16 07:12 UTC, krissi commented on lib/lib_storagetank.lua
I readded the size limitation and like in the warehouse mod I added a startup setting to disable the limit if desired

2023-03-19 13:42 UTC, merged

2023-03-19 13:42 UTC, nicolas-lang commented
not sure if I'll have time to release this weekend, I'll try to fix the release pipeline later this evening

2023-03-31 23:06 UTC, nicolas-lang commented
released.